<a href="https://colab.research.google.com/github/ujwaljain506-hash/ml-journey/blob/main/day16_model_predictions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
import matplotlib.pyplot as plt

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("/content/drive/MyDrive/matches.csv")
print("File Loaded")

File Loaded

In [8]:
le = LabelEncoder()
df['team1_encoded'] = le.fit_transform(df['team1'])
df['team2_encoded'] = le.fit_transform(df['team2'])
df['venue_encoded']=le.fit_transform(df['venue'])
df['toss_winner_encoded']=le.fit_transform(df['toss_winner'])
df['toss_decision_encoded']=le.fit_transform(df['toss_decision'])

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X = df[['team1_encoded', 'team2_encoded', 'venue_encoded', 'toss_winner_encoded', 'toss_decision_encoded']]
y = df['winner']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
print(X_train.shape)
print(X_test.shape)

(604, 5)
(152, 5)

In [13]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(random_state=42)

In [14]:
X_train.isnull().sum()

team1_encoded            0
team2_encoded            0
venue_encoded            0
toss_winner_encoded      0
toss_decision_encoded    0
dtype: int64

In [15]:
y_train.isnull().sum()

np.int64(4)

In [16]:
df[df['winner'].isnull()]

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,...,player_of_match,venue,umpire1,umpire2,umpire3,team1_encoded,team2_encoded,venue_encoded,toss_winner_encoded,toss_decision_encoded
300,301,IPL-2011,Delhi,21-05-2011,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,no result,0,...,NaN,Feroz Shah Kotla,SS Hazare,RJ Tucker,NaN,3,9,9,3,0
545,546,IPL-2015,Bangalore,29-04-2015,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,no result,0,...,NaN,M Chinnaswamy Stadium,JD Cloete,PG Pathak,NaN,13,10,17,10,1
570,571,IPL-2015,Bangalore,17-05-2015,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,no result,0,...,NaN,M Chinnaswamy Stadium,HDPK Dharmasena,K Srinivasan,NaN,3,13,17,13,1
744,11340,IPL-2019,Bengaluru,30-04-2019,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,no result,0,...,NaN,M. Chinnaswamy Stadium,Nigel Llong,Ulhas Gandhe,Anil Chaudhary,13,10,19,10,1

In [17]:
df = df.dropna(subset=['winner'])

In [18]:
df.shape

(752, 23)

In [19]:
X = df[['team1_encoded', 'team2_encoded', 'venue_encoded', 'toss_winner_encoded', 'toss_decision_encoded']]
y = df['winner']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [20]:
y_train.isnull().sum()

np.int64(0)

In [21]:
model.fit(X_train,y_train)

DecisionTreeClassifier(random_state=42)

In [22]:
y_pred = model.predict(X_test)

In [23]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.48344370860927155