<a href="https://colab.research.google.com/github/ujwaljain506-hash/ml-journey/blob/main/day5_groupby.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/matches.csv")
print("File Loaded")

File Loaded

In [3]:
df.groupby('winner').size()

winner
Chennai Super Kings            100
Deccan Chargers                 29
Delhi Capitals                  10
Delhi Daredevils                67
Gujarat Lions                   13
Kings XI Punjab                 82
Kochi Tuskers Kerala             6
Kolkata Knight Riders           92
Mumbai Indians                 109
Pune Warriors                   12
Rajasthan Royals                75
Rising Pune Supergiant          10
Rising Pune Supergiants          5
Royal Challengers Bangalore     84
Sunrisers Hyderabad             58
dtype: int64

In [4]:
df.groupby('winner')['win_by_runs'].mean()

winner
Chennai Super Kings            17.780000
Deccan Chargers                14.517241
Delhi Capitals                  9.200000
Delhi Daredevils               10.074627
Gujarat Lions                   0.076923
Kings XI Punjab                11.280488
Kochi Tuskers Kerala            3.833333
Kolkata Knight Riders          11.804348
Mumbai Indians                 17.119266
Pune Warriors                  11.583333
Rajasthan Royals               11.933333
Rising Pune Supergiant         12.300000
Rising Pune Supergiants        10.600000
Royal Challengers Bangalore    14.904762
Sunrisers Hyderabad            12.293103
Name: win_by_runs, dtype: float64